// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Hibernate() {
  return ObfuscatedCall(0, []);
}

export function Reboot() {
  return ObfuscatedCall(1, []);
}

export function Shutdown() {
  return ObfuscatedCall(2, []);
}
