// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Hibernate() {
  return window['go']['main']['App']['Hibernate']();
}

export function Reboot() {
  return window['go']['main']['App']['Reboot']();
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}
