// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Hibernate():Promise<void>;

export function Reboot():Promise<void>;

export function Shutdown():Promise<void>;
